### PR TITLE
Add support for alpine linux boxes

### LINKED ISSUE #4: Step succeeds when asset is not uploaded
When using this step with a box that does not contain the `jq` tool, the step will succeed despite an error being printed and no asset being uploaded.

Error message:
```
/pipeline/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86/run.sh: line 27: /pipeline/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86/bin/jq: No such file or directory
```

Succes statement:
```
successfully uploaded asset to GitHub
```

Full output:
```
export WERCKER_STEP_ROOT="/pipeline/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86"
export WERCKER_STEP_ID="github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="github-upload-asset"
export WERCKER_REPORT_NUMBERS_FILE="/report/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86/artifacts"
export WERCKER_GITHUB_UPLOAD_ASSET_TOKEN="${GITHUB_TOKEN}"
export WERCKER_GITHUB_UPLOAD_ASSET_FILE="website-${NEW_TAG}.zip"
source "/pipeline/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86/run.sh" < /dev/null
no name was supplied; using basename of $file: website-v2.0.3.zip
no GitHub owner was supplied; using GitHub owner of build repository: XXX
no GitHub repository was supplied; using GitHub repository of build: website
no content-type was supplied, using 'file' to get the content-type: application/zip
no release id was supplied, using release id from $WERCKER_GITHUB_CREATE_RELEASE_ID: 
no export id was supplied, using default value: WERCKER_GITHUB_UPLOAD_ASSET_ID
starting upload of asset website-v2.0.3.zip to GitHub repo XXX with release 
finished upload of asset website-v2.0.3.zip to GitHub repo XXX with release 
/pipeline/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86/run.sh: line 27: /pipeline/github-upload-asset-a859fa04-6482-4e39-a84d-fd95d385ba86/bin/jq: No such file or directory
exporting asset id () to environment variable: $WERCKER_GITHUB_UPLOAD_ASSET_ID
successfully uploaded asset to GitHub
```

### PR DESCRIPTION
**Pull request by miguelaferreira**
I've added an alpine compatible `jq`binary and a check to the run script that determines if the alpine based binary should be user.

I've pushed the code in this PR as a new step called 'github-upload-asset-forked' to test with. But cannot seem to pull it in my builds. I ran out of ideas on how to test this.

Fixes #4

### CODE REVIEW

**Comment by hatchan** [comment]
Looks like the latest version of jq works fine with Alpine. So will create a new version with just 1 binary

**Comment by miguelaferreira** [comment]
@hatchan do you have an ETA for a new version that works on Alpine?

**Comment by hatchan** [comment]
I'll release it first thing tomorrow

**Comment by miguelaferreira** [comment]
@hatchan did you manage to make a new release? My builds still break because of jq

**Comment by hatchan** [comment]
@miguelaferreira Yes I have released a new version

**Comment by miguelaferreira** [comment]
Thanks a bunch, my builds are running again.

**Pull request closed without merging**
